[package]
name = "bytes-rc"
description = "Single-threaded, Rc-based byte buffers compatible with bytes::Buf and BufMut"
version = "2.0.0"
edition = "2024"
rust-version = "1.100"
authors = ["loncothad <me@loncothad.cc>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/loncothad/bytes-rc"
readme = "README.md"
categories = ["data-structures"]
keywords = ["buffers", "bytes", "rc", "unsync"]
publish = true

[dependencies]
bytes = "1"

[lints.rust]
missing_docs = "deny"
non_ascii_idents = "forbid"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "deny"
undocumented_unsafe_blocks = "deny"
